### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by MouhamadDIMASSI** [RickardSjogren/vptree#13]
Hi 

I have a memory error on 10 000 points (1x45 dimension). 
What is the best practice to use vp-trees package without having a memory error.
Is it possible to run it on gpu ? 

Traceback (most recent call last):
 File "parquets_files_vptree.py", line 122, in <module>
   tree = vptree.VPTree(points, cosine)
 File "/usr/local/lib/python3.6/dist-packages/vptree.py", line 68, in __init__
   self.left = VPTree(points=left_points, dist_fn=self.dist_fn)
 File "/usr/local/lib/python3.6/dist-packages/vptree.py", line 71, in __init__
   self.right = VPTree(points=right_points, dist_fn=self.dist_fn)
 File "/usr/local/lib/python3.6/dist-packages/vptree.py", line 71, in __init__
   self.right = VPTree(points=right_points, dist_fn=self.dist_fn)
 File "/usr/local/lib/python3.6/dist-packages/vptree.py", line 40, in __init__
   points = np.delete(points, vp_i, axis=0)
 File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 4224, in delete
   new = empty(newshape, arr.dtype, arrorder)
MemoryError

**Comment by RickardSjogren** [comment]
How much memory does your machine have? A 10000x45-dataset is not very big.

I see you're using parquet-files, are you reading lazily from disk or is it loaded to memory?

**Comment by MouhamadDIMASSI** [comment]
It is loaded to memory and I have 56 GiB memory. I use NC6 serie gpu VM.
